version: '3.8'

services:
  

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectile-app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/projectile_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    command: ["pipenv", "run", "python", "./projectile/manage.py", "runserver", "0.0.0.0:8000"]
  
  db:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: